# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'JoelPipelineServiceConnection'
    organization: 'joelpipeline'
    scannerMode: 'MSBuild'
    projectKey: 'JoelPipeline_JoelPipelineProject'
    projectName: 'JoelPipelineProject'

- script: dotnet build ./12142020-dotnet-uta/JoelPipeline/P1/P1_JoelBarnum/P1_JoelBarnum.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'